[Database]
DSN = "database.db?_synchronous=OFF&_journal=WAL&cache=shared&_loc=auto&mode=rwc"

[App]
Debug = true

[App.Server]
IP = "127.0.0.1"
Port = 1991
ReadTimeout = "60s"
WriteTimeout = "60s"

# 事件调度器配置
[App.Event]
Async = true
Worker = 1
Capacity = 1000

# http请求方法欺骗配置
[App.Method]
Enable = true
Field = "_method"

# 静态文件服务配置
[App.StaticFile]
Enable = true
Path = ["/resources/asset", "/uploads"]
Referer = true

# session配置
[Session] # https://github.com/gorilla/sessions
Store = "cookie" # cookie|file
Name = "SESSION"
Key = "XUU1NDA4JXU0RTAwJXUzMDAy"

[Session.Options]
Path = "/"
Domain = ""
MaxAge = 0
Secure = false
HttpOnly = true
SameSite = 1

# http服务的日志器配置
[Log]
Async = true
Capacity = 1000
Level = "debug" # debug|info|notice|warning|error|critical|alert|emergency
Name = "default"
Path = "storage/logs"
Buffer = 4096
Flush = "5s"

# csrf防御配置
# https://github.com/gorilla/csrf
[CSRF]
Enable = true
Key = "32-byte-long-auth-key"
Name = "CSRF"
Field = "_token"
Header = "X-CSRF-Token"

[CSRF.Options]
Path = "/"
Domain = ""
MaxAge = 86400
Secure = false
HttpOnly = true

# gzip压缩配置
# https://github.com/nytimes/gziphandler
[GZIP]
Enable = true
Level = -1

# 静态资源打包配置
[Asset]
Dir = ["resources/...", "database/init.sql"]

# 业务相关配置
[Business]
# 超级管理员角色，添加节点的时候自动添加给当前角色
SuperRoleID = 1

# 上传配置
[Business.Upload]
# 允许是上传的文件的后缀
Ext = [
    "jpg", "jpeg",
    "gif",
    "png",
    "mp3",
    "mp4",
    "txt",
    "csv",
    "xls", "xlsx",
    "ppt", "pptx",
    "doc", "docx",
    "pdf",
    "zip"
]
# 允许上传的文件的media类型
# https://www.iana.org/assignments/media-types/media-types.xhtml
MimeTypes = [
    "image/jpeg",
    "image/gif",
    "image/png",
    "audio/mpeg",
    "video/mp4",
    "text/plain",
    "text/csv",
    "application/vnd.ms-excel", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "application/vnd.ms-powerpoint", "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    "application/msword", "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "application/pdf",
    "application/zip"
]
# 上传文件的保存目录
Save = "/uploads"