[Database]
# dsn参数 https://github.com/mattn/go-sqlite3
# ?_synchronous=OFF&_journal=WAL&cache=shared&_loc=auto&mode=rwc
DSN = "database.db"
# 设置连接池中的最大闲置连接数
MaxIdleConns = 50
# 设置与数据库建立连接的最大数目
MaxOpenConns = 100
# 设置缓存，如果为正数，则表示cache设置为多少页（默认页大小为1KB），如果为负数则表示设置为多少KB
CacheSize = 5000
# 控制台显示日志
ShowSQL = false

[App]
Debug = false

[App.Server]
# 如果配置为空，会自动获取本机公网ip地址
IP =""
# 测试环境可用用 https://github.com/FiloSottile/mkcert 生成测试的证书
CertFile = ""
KeyFile = ""
Port = 80
ReadTimeout = "60s"
WriteTimeout = "60s"
# 进程收到信号后，服务强制关闭时间
CloseTimedOut = "60s"

# 事件调度器配置
[App.Event]
Async = true
Worker = 1
Capacity = 1000
CloseTimedOut = "1s"

# http请求方法欺骗配置
[App.Method]
Enable = true
Field = "_method"

# 静态文件服务配置
[App.StaticFile]
Enable = true
Path = ["/resources/asset", "/uploads"]
Referer = true

# session配置
[Session] # https://github.com/gorilla/sessions
Store = "cookie" # cookie|file
Name = "SESSION"
Key = "XUU1NDA4JXU0RTAwJXUzMDAy"

[Session.Options]
Path = "/"
Domain = ""
# MaxAge=0 表示未指定Max Age属性，浏览器会话结束后将删除cookie
# MaxAge<0 意味着立即删除cookie
# MaxAge>0 表示存在并以秒为单位给定的最大时长
MaxAge = 3600
Secure = false
HttpOnly = true
SameSite = 1

# http服务的日志器配置
[Log]
Async = true
Capacity = 1000
Level = "debug" # debug|info|notice|warning|error|critical|alert|emergency
Name = "default"
Path = "storage/logs"
Buffer = 4096
Flush = "5s"
CloseTimedOut = "1s"

# 页面缓存
[Cache]
Enable = false
Path = "storage/cache"

# csrf防御配置
# https://github.com/gorilla/csrf
[CSRF]
Enable = true
Key = "32-byte-long-auth-key"
Name = "CSRF"
Field = "_token"
Header = "X-CSRF-Token"

[CSRF.Options]
Path = "/"
Domain = ""
MaxAge = 86400
Secure = false
HttpOnly = true

# gzip压缩配置
# https://github.com/nytimes/gziphandler
[GZIP]
Enable = true
Level = -1

# 静态资源打包配置
[Asset]
Dir = ["resources/...", "database/init.sql"]

# 业务相关配置
[Business]
# 超级管理员角色，添加节点的时候自动添加给当前角色
SuperRoleID = 1

# 上传配置
[Business.Upload]
# 上传文件的保存目录
Save = "/uploads"
# 允许上传的文件的后缀与media类型
# https://www.iana.org/assignments/media-types/media-types.xhtml
[Business.Upload.Accept]
jpg = "image/jpeg"
jpeg = "image/jpeg"
gif = "image/gif"
png = "image/png"
mp3 = "audio/mpeg"
mp4 = "video/mp4"
txt = "text/plain"
js = "application/javascript"
json = "application/json"
csv = "text/csv"
xls = "application/vnd.ms-excel"
xlsx = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
ppt = "application/vnd.ms-powerpoint"
pptx = "application/vnd.openxmlformats-officedocument.presentationml.presentation"
doc = "application/msword"
docx = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
pdf = "application/pdf"
zip = "application/zip"
rar = "application/octet-stream"
go = ""
php = ""
java = ""
c = ""
py = ""

# 第三方登录配置
[Business.OAuth]
[Business.OAuth.User]
Identity = 0
RoleID = 0
[Business.OAuth.List.github]
ID = ""
Secret = ""
CallBackUrl = ""
