[Database]
DSN = "database.db?_synchronous=OFF&_journal=WAL&_loc=auto&cache=shared&mode=rwc"

[App]
Debug = true

[App.Server]
IP = "127.0.0.1"
Port = 1991
ReadTimeout = "60s"
WriteTimeout = "60s"

[App.Event]
Async = true
Worker = 1
Capacity = 1000

[App.Method]
Enable = true
Field = "_method"

[App.StaticFile]
Enable = true
Path = ["/resources/asset", "/uploads"]
Referer = true

[Session] # https://github.com/gorilla/sessions
Store = "cookie" # cookie|file
Name = "SESSION"
Key = "XUU1NDA4JXU0RTAwJXUzMDAy"

[Session.Options]
Path = "/"
Domain = ""
MaxAge = 0
Secure = false
HttpOnly = true
SameSite = 1

[Log]
Async = true
Capacity = 1000
Level = "debug" # debug|info|notice|warning|error|critical|alert|emergency
Name = "default"
Path = "storage/logs"
Buffer = 4096
Flush = "5s"

[CSRF] # https://github.com/gorilla/csrf
Enable = true
Key = "32-byte-long-auth-key"
Name = "CSRF"
Field = "_token"
Header = "X-CSRF-Token"

[CSRF.Options]
Path = "/"
Domain = ""
MaxAge = 86400
Secure = false
HttpOnly = true

[GZIP] # https://github.com/nytimes/gziphandler
Enable = true
Level = -1

[Asset]
Dir = ["resources/..."]

[Business]
SuperRoleID = 1

[Business.Upload]
Ext = [
    "jpg", "jpeg",
    "gif",
    "png",
    "mp3",
    "mp4",
    "txt",
    "csv",
    "xls", "xlsx",
    "ppt", "pptx",
    "doc", "docx",
    "pdf",
    "zip"
]
# https://www.iana.org/assignments/media-types/media-types.xhtml
MimeTypes = [
    "image/jpeg",
    "image/gif",
    "image/png",
    "audio/mpeg",
    "video/mp4",
    "text/plain",
    "text/csv",
    "application/vnd.ms-excel", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "application/vnd.ms-powerpoint", "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    "application/msword", "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "application/pdf",
    "application/zip"
]
Save = "/uploads"